# Generated by Django 2.2.7 on 2019-11-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcrush',
            name='crush1_message',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='crush1_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='crush2_message',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='crush2_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='crush3_message',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='crush3_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='crush4_message',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='crush4_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='crush5_message',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='crush5_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
