# Generated by Django 2.2.7 on 2019-12-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hidentouser',
            name='lastname',
        ),
        migrations.AddField(
            model_name='hidentouser',
            name='fullname',
            field=models.CharField(default='defaultfullname', max_length=255),
            preserve_default=False,
        ),
    ]
