# Generated by Django 2.2.7 on 2019-12-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controls',
            name='total_female_users',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controls',
            name='total_male_users',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controls',
            name='total_other_gender_users',
            field=models.BigIntegerField(default=0),
        ),
    ]
