# Generated by Django 2.2.7 on 2019-11-21 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hidentouser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='hidentouser',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='instagramcrush',
            name='hidento_userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagramDetails', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
