# Generated by Django 2.2.7 on 2020-09-14 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymousmessage',
            old_name='receiver_instagram_username',
            new_name='receiver_instagram_username1',
        ),
        migrations.RemoveField(
            model_name='anonymousmessage',
            name='sender_nickname',
        ),
        migrations.AddField(
            model_name='anonymousmessage',
            name='receiver_instagram_username2',
            field=models.CharField(default='default_receiver2', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymousmessage',
            name='hidento_userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='anonymousSentMessages', to=settings.AUTH_USER_MODEL),
        ),
    ]
