# Generated by Django 2.2.7 on 2019-12-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hidentouser',
            name='joined_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='old_match_broken_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='old_match_instagram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='old_match_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
