# Generated by Django 2.2.7 on 2020-01-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramdetails',
            name='ll_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='instagramdetails',
            name='token_expires_in',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagramdetails',
            name='token_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
