# Generated by Django 2.2.7 on 2019-11-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0002_auto_20191126_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcrush',
            name='crush1_whomToInform',
            field=models.IntegerField(choices=[(1, 'Choose at random'), (2, 'Inform my crush')], default=1),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='crush2_whomToInform',
            field=models.IntegerField(choices=[(1, 'Choose at random'), (2, 'Inform my crush')], default=1),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='crush3_whomToInform',
            field=models.IntegerField(choices=[(1, 'Choose at random'), (2, 'Inform my crush')], default=1),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='crush4_whomToInform',
            field=models.IntegerField(choices=[(1, 'Choose at random'), (2, 'Inform my crush')], default=1),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='crush5_whomToInform',
            field=models.IntegerField(choices=[(1, 'Choose at random'), (2, 'Inform my crush')], default=1),
        ),
    ]
