# Generated by Django 2.2.7 on 2020-02-03 15:48

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0002_auto_20200201_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBlacklist',
            fields=[
                ('hidento_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='messageBlacklist', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('blacklistJSON', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('last_modified_time', models.DateTimeField()),
            ],
        ),
    ]
