# Generated by Django 2.2.7 on 2019-12-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0002_auto_20191209_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHidento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField(max_length=3000)),
                ('reply_email_subject', models.CharField(blank=True, max_length=300, null=True)),
                ('reply_email_message', models.TextField(blank=True, max_length=6000, null=True)),
                ('action', models.IntegerField(choices=[(3, 'Do Nothing'), (2, 'Send Reply and Move to Replied'), (1, 'Move to Replied'), (4, 'Delete')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='ContactHidentoReplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField(max_length=3000)),
                ('reply_email_subject', models.CharField(blank=True, max_length=300, null=True)),
                ('reply_email_message', models.TextField(blank=True, max_length=6000, null=True)),
                ('action', models.IntegerField(choices=[(1, 'Do Nothing'), (2, 'Send Reply'), (3, 'Delete')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=3000)),
                ('answer', models.TextField(max_length=10000)),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority_value', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(max_length=3000)),
                ('explanation', models.TextField(max_length=10000)),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority_value', models.IntegerField(default=1)),
            ],
        ),
    ]
