# Generated by Django 2.2.7 on 2020-09-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0002_auto_20200914_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousmessage',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
