# Generated by Django 2.2.7 on 2019-11-23 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0002_auto_20191121_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcrush',
            name='hidento_userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='instagramDetails', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instagramcrush',
            name='instagram_userid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
