# Generated by Django 2.2.7 on 2020-01-30 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0002_auto_20200122_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousMessage',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('sender_instagram_username', models.CharField(max_length=255)),
                ('receiver_instagram_username', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('sender_nickname', models.CharField(max_length=100)),
                ('added_time', models.DateTimeField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_abusive', models.BooleanField(default=False)),
                ('hidento_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymousSentMessages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
