# Generated by Django 2.2.7 on 2020-09-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0003_auto_20200915_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymousmessage',
            old_name='is_hidden',
            new_name='is_hidden1',
        ),
        migrations.AddField(
            model_name='anonymousmessage',
            name='is_hidden2',
            field=models.BooleanField(default=False),
        ),
    ]
