# Generated by Django 2.2.7 on 2020-01-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0003_anonymousmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousmessage',
            name='sender_instagram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
