# Generated by Django 2.2.7 on 2019-12-09 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0003_contacthidento_contacthidentoreplied_faq_howitworks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactHidentoReplied',
        ),
        migrations.AddField(
            model_name='contacthidento',
            name='contact_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contacthidento',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacthidento',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacthidento',
            name='is_successfully_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacthidento',
            name='replied_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacthidento',
            name='action',
            field=models.IntegerField(choices=[(1, 'Do Nothing'), (2, 'Send Reply'), (3, 'Delete')], default=1),
        ),
    ]
