# Generated by Django 2.2.7 on 2020-02-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0004_auto_20200130_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousmessage',
            name='receiver_instagram_username',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='anonymousmessage',
            name='sender_instagram_username',
            field=models.CharField(default='not_set', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymousmessage',
            name='sender_nickname',
            field=models.CharField(max_length=50),
        ),
    ]
