# Generated by Django 2.2.7 on 2019-11-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretcrushapp', '0004_auto_20191129_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcrush',
            name='match_message',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instagramcrush',
            name='match_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
