"""
Django settings for hidento_project project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import json

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
try:
    with open('/etc/hidento_project_config.json') as config_file:
        config = json.load(config_file)

        SECRET_KEY = config['SECRET_KEY']

        EMAIL_HOST = config['EMAIL_HOST']
        EMAIL_PORT = config['EMAIL_PORT']
        EMAIL_HOST_USER = config['EMAIL_HOST_USER']
        EMAIL_HOST_PASSWORD = config['EMAIL_HOST_PASSWORD']
        EMAIL_USE_TLS = config['EMAIL_USE_TLS']
        DEFAULT_FROM_EMAIL = config['DEFAULT_FROM_EMAIL']
        SUPPORT_FROM_EMAIL = config['SUPPORT_FROM_EMAIL']

        INSTAGRAM_APP_SECRET = config['INSTAGRAM_APP_SECRET']

        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql_psycopg2',
                'NAME': config['DB_NAME'],
                'USER': config['DB_USER'],
                'PASSWORD': config['DB_PASSWORD'],
                'HOST': config['DB_HOST'],
                'PORT': config['DB_PORT'],
            }
        }
except FileNotFoundError as error:
    pass

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['www.hidento.com', 'hidento.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_user_agents',
    'secretcrushapp.apps.SecretcrushappConfig',
    'django_simple_bulma',
]

USER_AGENTS_CACHE = 'default'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = 'hidento_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'secretcrushapp.custom_context_processor.secretcrushapp_context_processor',
            ],
        },
    },
]

STATICFILES_FINDERS = [
  # First add the two default Finders, since this will overwrite the default.
  'django.contrib.staticfiles.finders.FileSystemFinder',
  'django.contrib.staticfiles.finders.AppDirectoriesFinder',

  # Now add our custom SimpleBulma one.
  'django_simple_bulma.finders.SimpleBulmaFinder',
]

WSGI_APPLICATION = 'hidento_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

AUTH_USER_MODEL = 'secretcrushapp.HidentoUser'
AUTHENTICATION_BACKENDS = ['secretcrushapp.views.HidentoUserBackend']
LOGIN_REDIRECT_URL ='index'
LOGOUT_REDIRECT_URL = 'index'
LOGIN_URL = 'login'

#Instagram related settings
INSTAGRAM_APP_ID = 568134807270658
INSTAGRAM_AUTHORIZE_URL = 'https://api.instagram.com/oauth/authorize'
INSTAGRAM_AUTHORIZE_REDIRECT_URL = 'https://www.hidento.com/account/instagram/auth/'
INSTAGRAM_TOKEN_URL = 'https://api.instagram.com/oauth/access_token'
INSTAGRAM_USERNODE_URL = 'https://graph.instagram.com/'


#Logging settings
LOG_FILE_PATH = '/home/ubuntu/logs/secretcrushapp_log.log'

#App settings
STABLIZATION_PERIOD = 7
STABLE_PERIOD = 14
CONTROLS_RECORD_ID = 'master_controls'

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT  = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

try:
    from .settings_bulma import *
    from .settings_local import *
except ImportError as e:
    pass