"""
Django settings for hidento_project project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import json

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY_HOLDER = ''

EMAIL_HOST_HOLDER = ''
EMAIL_PORT_HOLDER = 80
EMAIL_HOST_USER_HOLDER = ''
EMAIL_HOST_PASSWORD_HOLDER = ''
EMAIL_USE_TLS_HOLDER = True
DEFAULT_FROM_EMAIL_HOLDER = ''
INSTAGRAM_APP_SECRET_HOLDER = ''

try:
    with open('/etc/hidento_project_config.json') as config_file:
        config = json.load(config_file)

        SECRET_KEY_HOLDER = config['SECRET_KEY']

        EMAIL_HOST_HOLDER = config['EMAIL_HOST']
        EMAIL_PORT_HOLDER = config['EMAIL_PORT']
        EMAIL_HOST_USER_HOLDER = config['EMAIL_HOST_USER']
        EMAIL_HOST_PASSWORD_HOLDER = config['EMAIL_HOST_PASSWORD']
        EMAIL_USE_TLS_HOLDER = config['EMAIL_USE_TLS']
        DEFAULT_FROM_EMAIL_HOLDER = config['DEFAULT_FROM_EMAIL']

        INSTAGRAM_APP_SECRET_HOLDER = config['INSTAGRAM_APP_SECRET']
except FileNotFoundError as error:
    pass

SECRET_KEY = SECRET_KEY_HOLDER

EMAIL_HOST = EMAIL_HOST_HOLDER
EMAIL_PORT = EMAIL_PORT_HOLDER
EMAIL_HOST_USER = EMAIL_HOST_USER_HOLDER
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD_HOLDER
EMAIL_USE_TLS = EMAIL_USE_TLS_HOLDER
DEFAULT_FROM_EMAIL = DEFAULT_FROM_EMAIL_HOLDER

INSTAGRAM_APP_SECRET = INSTAGRAM_APP_SECRET_HOLDER

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['www.hidento.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'secretcrushapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hidento_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hidento_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': '/etc/mysql/my.cnf',
        },
    }
}

AUTH_USER_MODEL = 'secretcrushapp.HidentoUser'
AUTHENTICATION_BACKENDS = ['secretcrushapp.views.HidentoUserBackend']
LOGIN_REDIRECT_URL ='index'
LOGOUT_REDIRECT_URL = 'index'
LOGIN_URL = 'login'

#Instagram related settings
INSTAGRAM_APP_ID = 568134807270658
INSTAGRAM_AUTHORIZE_URL = 'https://api.instagram.com/oauth/authorize'
INSTAGRAM_AUTHORIZE_REDIRECT_URL = 'https://www.hidento.com/account/instagram/auth/'
INSTAGRAM_TOKEN_URL = 'https://api.instagram.com/oauth/access_token'
INSTAGRAM_USERNODE_URL = 'https://graph.instagram.com/'

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT  = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

try:
    from .settings_local import *
except ImportError as e:
    pass